### ISSUE TITLE
A headache to install and compile the R

### ISSUE THREAD

**Issue by unclecode** [r-wasm/webr#78] opened 2022-10-26 05:49 UTC
I used an Ubuntu distro, then just ran ./configure, and it took hours plus fixing a lot of issues and error messages, but finally, it happened. And then for the "make" step, again, I had a lot of problems, I fixed them, and eventually, I came to this error. I will give up unless you can help me please.

```
ubuntu@ip-ubuntu@ip-XXX-XXX:~/webR$ sudo make
cd R && make && make install
make[1]: Entering directory '/home/ubuntu/webR/R'
mkdir -p /home/ubuntu/webR/R/build/R-4.1.3/build-stage1/doc
cd /home/ubuntu/webR/R/build/R-4.1.3/build-stage1/doc && \
  touch NEWS NEWS.pdf NEWS.rds NEWS.2.rds NEWS.3.rds
cd /home/ubuntu/webR/R/build/R-4.1.3/build-stage1 && \
  FC="gfortran" \
    CXX="clang  " \
    CC="clang" \
    FC="gfortran" \
    CPPFLAGS="" \
    CFLAGS="" \
    LDFLAGS="" \
    ../configure \
      --prefix="/home/ubuntu/webR/host/R-4.1.3" \
      --with-x=no \
      --with-readline=no \
      --with-jpeglib=no \
      --with-cairo=no \
      --disable-openmp \
      --with-recommended-packages=no \
      --enable-R-profiling=no \
      --with-pcre2 \
      --disable-nls \
      --enable-byte-compiled-packages=no \
      --enable-long-double=no
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
loading site script '../config.site'
checking for pwd... /usr/bin/pwd
checking whether builddir is srcdir... no
checking whether ln -s works... yes
checking for ar... ar
checking for a BSD-compatible install... /usr/bin/install -c
checking for sed... /usr/bin/sed
checking for which... /usr/bin/which
checking for less... /usr/bin/less
checking for gtar... no
checking for gnutar... no
checking for tar... /usr/bin/tar
checking for tex... no
checking for pdftex... no
configure: WARNING: you cannot build PDF versions of the R manuals
checking for pdflatex... no
configure: WARNING: you cannot build PDF versions of vignettes and help pages
checking for makeindex... no
checking for texi2any... no
configure: WARNING: you cannot build info or HTML versions of the R manuals
checking for texi2dvi... no
checking for kpsewhich... no
checking for latex inconsolata package... checking for unzip... no
checking for zip... no
checking for gzip... /usr/bin/gzip
checking for bzip2... /usr/bin/bzip2
checking for firefox... no
checking for mozilla... no
checking for galeon... no
checking for opera... no
checking for xdg-open... no
checking for kfmclient... no
checking for gnome-moz-remote... no
checking for open... no
configure: WARNING: I could not determine a browser
checking for acroread... no
checking for acroread4... no
checking for xdg-open... no
checking for evince... no
checking for xpdf... no
checking for gv... no
checking for gnome-gv... no
checking for ggv... no
checking for okular... no
checking for kpdf... no
checking for open... no
checking for gpdf... no
checking for kghostview... no
configure: WARNING: I could not determine a PDF viewer
checking for working aclocal... missing
checking for working autoconf... missing
checking for working autoheader... missing
checking for bison... no
checking for byacc... no
checking for yacc... no
checking for notangle... false
checking for realpath... /usr/bin/realpath
checking for pkg-config... no
checking for pkgconf... no
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/home/ubuntu/webR/R/build/R-4.1.3/build-stage1':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[1]: *** [Makefile:74: /home/ubuntu/webR/R/build/state/r-stage1-configured] Error 77
make[1]: Leaving directory '/home/ubuntu/webR/R'
make: *** [Makefile:13: webr] Error 2
ubuntu@ip-XXX-XXX:~/webR$  
```

**Comment by georgestagg** [comment] 2022-10-26 07:33
It looks like clang is there, but some other development environment tools are missing. You could try the following, which will set up a basic development environment in Ubuntu,

```
sudo apt install build-essential
```

Do you have much previous experience building unix packages from source? If not, it might be a good idea to wait until the first versioned release of webR, which will come with pre-compiled WASM binaries released on GitHub as a downloadable archive and also hosted on a CDN.

**Comment by unclecode** [comment] 2022-10-26 07:54
> stall build-essential

Of course, the "build-essentials" is there. That is not the problem. The problem lies elsewhere. Is it possible to share the precompiled WASM you are using now on the demo site? And when do you think this pro compiled will come out?

**Comment by georgestagg** [comment] 2022-10-26 08:11
OK. The exact issue leading to the `C compiler cannot create executables` message should be visible in the log file `config.log`. These files are a little hard to read if you are not used to them, though.

Since the problem is in the configure step of "build-stage1", which just creates a local build of R for the host machine, I would suggest downloading the R source and seeing if you can build that first. I suspect the issue you are seeing will apply to a standard build of R's source, too. If it is so, debugging the problem should be easier there.

I do not have an exact date for the first versioned release, but once it has been tagged it will be available on the GitHub Releases page for this repo.

**Comment by unclecode** [comment] 2022-10-27 03:51
I've checked the configuration file and yes, it's difficult to figure out. You have a point about compiling R separately. So do you mean I replace the current R source code in the folder with a new one that I have to download and try to compile?

**Comment by unclecode** [comment] 2022-10-27 12:57
I tried that, and at first seems working but stop at a new error. I share here my config.log file. Hope you can help me. I really need to try this R on browser. This is the linl for config file. It is too big, so have to upload it. 

https://file.io/cibVf5q2dpPw

**Comment by frafra** [comment] 2022-11-29 09:36
Just some tips: avoid use `sudo` to run `make`, and check if you have clang. emscripten requires clang, and make should be configured to use that, using the `CC` environmental variable.

**Comment by georgestagg** [comment] 2023-03-20 14:22
It looks like this issue has been quiet for a few months now, so I'm going to close it.

As requested in the thread, a pre-compiled version of webR, and an npm package, are now available for general use. New users no longer have to compile webR from scratch themselves. Releases are available at https://github.com/r-wasm/webr/releases and documentation at https://docs.r-wasm.org/webr/latest/

If you are still having issues using the release version of webR, please feel free to open a new issue.

**Closed by georgestagg** 2023-03-20 14:22 UTC
