### ISSUE TITLE
Enhancement: RPostgreSQL for webR

### ISSUE THREAD

**Issue by SugarRayLua** [r-wasm/webr#287] opened 2023-10-04 04:29 UTC

**Comment by georgestagg** [comment] 2023-10-31 15:38
Thanks for the feature request!

In principle, this depends on external networking for connecting to databases such as postgreSQL. As such, the issue is also covered by #129. I'm going to close this one in favour of tracking things there.

**Closed by georgestagg** 2023-10-31 15:38 UTC

**Comment by SugarRayLua** [comment] 2023-11-01 01:15
Thank you for the update and considering the request :-)

**Comment by gregvolny** [comment] 2024-10-08 00:07
> Thanks for the feature request!
> 
> In principle, this depends on external networking for connecting to databases such as postgreSQL. As such, the issue is also covered by #129. I'm going to close this one in favour of tracking things there.

Others found some working solution for networking/Database access from the browser. Please take a look on this repo: https://github.com/stack-auth/pgmock

**Comment by SugarRayLua** [comment] 2024-10-08 17:24
Wonderful, thanks!
