### ISSUE TITLE
Could not load dynamic lib: /usr/lib/R/library/nloptr/libs/nloptr.so

### ISSUE THREAD

**Issue by erex** [r-wasm/webr#349] opened 2024-01-04 19:55 UTC
Experimenting with Webr with a package that depends upon the package `nloptr`. When loading the `mrds` package, (with `nloptr` dependency) this message arises:

```
Error: package or namespace load failed for ‘mrds’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib/R/library/nloptr/libs/nloptr.so':
  Could not load dynamic lib: /usr/lib/R/library/nloptr/libs/nloptr.so
Error: bad export type for `nlopt_get_initial_step`: undefined
```

Message appears even though both `mrds` and `nloptr` show on `https://repo.r-wasm.org/` to have no missing dependencies.

### Reproducible example (Quarto document in Windows 11):

```
---
title: "Experiment"
filters: 
  - webr
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

```{webr-r}
webr::install("nloptr")
```

```{webr-r}
webr::install("mrds")
```

```{webr-r}
webr::install("Distance")
```

```{webr-r}
library(mrds)
library(Distance)
```

```{webr-r}
data("ducknest")
cu <- convert_units("meter", "kilometer", "square kilometer")
```

**Comment by jeroen** [comment] 2024-01-05 10:17
Something is going wrong with the build. I think the problem is that we don't have any libnlopt in https://github.com/r-wasm/webr/tree/main/libs/recipes and then the package tries to fall back to building a local copy using cmake, but that does not seem to work.

The easiest solution is probably to add nlopt to [webr recipes](https://github.com/r-wasm/webr/tree/main/libs/recipes)

**Comment by erex** [comment] 2024-01-05 10:31
thanks for the investigation @jeroen. Your solution is beyond my abilities, hopefully one of the contributors can make that modification.

**Comment by jeroen** [comment] 2024-01-15 15:30
This is fixed now, can be closed.

**Closed** 2024-04-02 11:34 UTC
