### ISSUE TITLE
mgcv errors on demo page

### ISSUE THREAD

**Issue by noamross** [r-wasm/webr#170] opened 2023-03-10 12:57 UTC
Hello! Excellent work with this project. When running the demo at https://webr.r-wasm.org/latest, I get the following error:

```
> webr::install("mgcv")
Downloading webR package: lattice
Downloading webR package: nlme
Downloading webR package: Matrix
Downloading webR package: mgcv
> mod <- mgcv::gam(hp ~ s(disp), data=mtcars)

fatal Fortran runtime error(./../../../../src/modules/lapack/dlapack.f:114618): Internal error: RUNTIME_CHECK(catKind.has_value()) failed at extrema.cpp(243)
Aborted()
```

**Comment by georgestagg** [comment] 2023-03-21 11:08
Thank you for this bug report.

To build webR we are using an early development version of LLVM flang to compile LAPACK Fortran source code included in the base R distribution into WebAssembly. This flang compiler is not yet stable, and we are aware of a few issues that affect our wasm build of LAPACK. We expect that over time the development of flang will mature and issues like this one will go away as we upgrade the version of LLVM that we are using.

I've merged a patch that works around this particular error, as it also solves a problem in an unrelated function in base R (details are in the linked PR above). Do note, however, that while the patch does also help with mgcv, in this case it is not sufficient. From my limited further testing of mgcv, there are still some numerical convergence issues, most likely caused by other problematic Fortran code that mgcv relies on.

So, I am going to leave this issue open for now and we can check how things stand in the future once when we have upgraded the LLVM branch or release that we're based on. To help when revisiting in future, the following is a short example of the current state of running mgcv code, demonstrating the convergence issues.


RUNS:
```
> mod <- mgcv::bam(hp ~ s(disp), data=mtcars)
```

FAILS:
```
> mod <- mgcv::gam(hp ~ s(disp), data=mtcars)
Error in magic(G$y, G$X, msp, G$S, G$off, L = G$L, lsp0 = G$lsp0, G$rank,  : 
  magic, the gcv/ubre optimizer, failed to converge after 400 iterations.
```

**Closed** 2023-12-08 08:55 UTC
Labels: bug
