### ISSUE TITLE
Embed PostgreSQL in the WebR virtual file system as an alternative to DBI

### ISSUE THREAD

**Issue by gregvolny** [r-wasm/webr#490] opened 2024-09-27 23:54 UTC
### Are you requesting a feature, reporting a bug or asking a question?
I'm Requesting a new feature.

### What is the current behavior?
Right now, It's almost impossible for accessing remote relational database from WebR. However, because of the new PGLite: https://github.com/electric-sql/pglite, this could be changed in the future if you integrate it in the WebR API. If implemented,  we can have  persistent or in memory relational database in the Browser virtual file system. 

### What is the expected behavior?
If implemented, we can have persistent data on any device. WebR can have access to relational data stored in remote Postgre servers because the local (in memory or persistent) Postgre database can sync to remote centralized PG servers using https://pglite.dev/docs/sync or other (future) JS Postgre sync engine or packages.

**Comment by seanbirchall** [comment] 2024-10-08 13:27
Postgres is great I'm not very familiar with pglite though, but get the idea looking at the repo. Could you not just import these dependencies into your shinylive app and access the pglite instance from the shinylive app via javascript?

**Comment by georgestagg** [comment] 2024-10-11 08:18
I'm going to close this in favour of #129. Also essentially a duplicate of #287, closed for the same reason.

Feel free to continue this conversation in #129, but please do not open any further new issues about it. This makes tracking much easier for maintainers and other interested users.

It sounds like the [sync approach ](https://pglite.dev/docs/sync) for pglite would indeed work, but I think it would be better implemented in a new `pglite`  R package rather than in the core of webR itself. Similar to the `duckdb` package, or the `RSQLite` package, both of which can currently be used in webR to perform in-process database operations.

The persistence of on-disk database files in webR can also already be achieved using the Emscripten `IDBFS` filesystem driver: [documentation here](https://docs.r-wasm.org/webr/latest/mounting.html#indexeddb-filesystem-storage).

The difficult part is remote database connections, covered by the issue #129. I have already described in that issue why this is more difficult for us in webR than for other projects that have solved similar problems, at least until stack-switching/JSPI is more readily available in browsers without debugging flags.

**Closed as not planned by georgestagg** 2024-10-11 08:18 UTC
