### ISSUE TITLE
Help me with this 

### ISSUE THREAD

**Issue by econstar** [r-wasm/webr#497] opened 2024-11-07 07:02 UTC
**Warning messages:** 

1: Can't find MASS in webR binary repository. 2: Can't find Matrix in webR binary repository. 3: Can't find curl in r-universe binary repository. 4: Package version mismatch for xfun, ensure the versions below are compatible. ! Installed version: 0.49, WebAssembly version: 0.48. ℹ Install a package version matching the WebAssembly version to silence this error.

What CAN I DO

**Comment by georgestagg** [comment] 2024-12-16 13:44
This looks like it might be output from running Shinylive for R.

I have checked the `MASS` and `Matrix` packages do appear to be working: [example](https://shinylive.io/r/examples/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IdJiw71OY4aIbM27ALIBBAMprZYhRyVRSjWgA9ZIgK60ABAB4AtJbqdS7EZcsA3OI3r7aMACpwRqQA8makqOEuYO60cADuQmCyphCcXp6MNvYAZmYQBKS0JOx8kaS4lkTh5QKWIK6WjTDZlpyoLOl6BsallgC8lgTsAMyVAIyVI4gATJUziOMClagDQ+wADLOVACy7lQBsy5ZGa+OIB7iNACZ+0PCca47OADIAov7+b1hqwOcjAF1KtQ4KRyIxOH9EABWAECWRuMwEDatADC3CIIM4AGsOCpWgRGEROO0idd2DA6gBqSwAEVoUAA5iQoNR2ND4Y1qhFwgASWIJVqMCjXLwABUMZHYDQgbjcqElziRGwRlgAvrI1SIRDw+KwVOh2BY1hZKulGJk1ubMrIwGqAUA).

If you continue to find that Matrix and MASS are not being found, please can you create a minimal reproducible example app that demonstrates the problem, and open a new issue at https://github.com/posit-dev/r-shinylive/issues. Such an example app will help us to track down exactly what is going wrong.

----

The `curl` package does not currently work in webR. If `curl` is a dependency for a package you require then your app cannot work in Shinylive for the moment. You might be able to work around it by using base R `url()` or `download.file()`.

----

I'm going to close this particular issue, since I can't transfer it directly to the Shinylive repo issues.

**Closed as not planned by georgestagg** 2024-12-16 13:44 UTC
