### ISSUE TITLE
The mmrm package is missing again

### ISSUE THREAD

**Issue by adrianolszewski** [r-wasm/webr#429] opened 2024-05-30 02:55 UTC
Hello,
I just tried the mmrm package in the latest web R version: https://webr.r-wasm.org/latest/
and it disappear again:

```
> library(mmrm)
Failed to load package "mmrm". Do you want to try downloading it from the webR binary repo? 

1: Yes
2: No

Selection: 1
Warning message:
In webr::install(package) :
  Requested package mmrm not found in webR binary repo.
```
I tried it 30.05.2024.

![obraz](https://github.com/r-wasm/webr/assets/95669100/54a19e7b-449a-4f61-94f1-14158f6be8c8)

**Comment by georgestagg** [comment] 2024-05-30 09:56
Thanks for reporting this!

Closing as duplicate of #391, I've written a longer reply there.

**Closed by georgestagg** 2024-05-30 09:56 UTC
